source 'https://rubygems.org'

gem 'grape'
gem 'rake'
gem 'json'
gem 'rack'
gem 'grape-entity'
gem 'rack-cors'
gem 'nokogiri'
gem 'zip'
gem 'hashie'
gem 'omniauth'
gem 'actionpack'
gem 'girl_friday'
gem 'typhoeus'
gem 'elasticsearch'
gem 'puma'

group :development, :test do
  gem 'better_errors'
  gem 'rspec'
  gem 'rack-test'
  gem 'rack-contrib'
  gem 'rubocop'
  gem 'guard'
  gem 'guard-rspec'
  gem 'guard-rubocop'
  gem 'guard-bundler'
  gem 'guard-rack'
  gem 'guard-yard'
  gem 'guard-ctags-bundler'
  gem 'ruby_gntp'
  gem 'foreman'
  gem 'yard'
  gem 'redcarpet'
  gem 'github-markup'
  gem 'cookiejar'
end
